name: mi_app
description: A new Flutter project

publish_to: 'none' # Remove this line if you're planning to publish your app

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0  # Otras dependencias de tu proyecto
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Dependencias de desarrollo

flutter:
  uses-material-design: true



